/*

 BLACKSCRTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __BlackScrTiles_h_INCLUDE
#define __BlackScrTiles_h_INCLUDE

/* Bank of tiles. */
#define BlckScrTilesBank 0

/* Super Gameboy palette 0 */
#define BlckScrTilesSGBPal0c0 6076
#define BlckScrTilesSGBPal0c1 8935
#define BlckScrTilesSGBPal0c2 6596
#define BlckScrTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BlckScrTilesSGBPal1c0 6076
#define BlckScrTilesSGBPal1c1 8935
#define BlckScrTilesSGBPal1c2 6596
#define BlckScrTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BlckScrTilesSGBPal2c0 6076
#define BlckScrTilesSGBPal2c1 8935
#define BlckScrTilesSGBPal2c2 6596
#define BlckScrTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BlckScrTilesSGBPal3c0 6076
#define BlckScrTilesSGBPal3c1 8935
#define BlckScrTilesSGBPal3c2 6596
#define BlckScrTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BlckScrTilesCGBPal0c0 0
#define BlckScrTilesCGBPal0c1 0
#define BlckScrTilesCGBPal0c2 0
#define BlckScrTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define BlckScrTilesCGBPal1c0 6076
#define BlckScrTilesCGBPal1c1 8935
#define BlckScrTilesCGBPal1c2 6596
#define BlckScrTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define BlckScrTilesCGBPal2c0 6076
#define BlckScrTilesCGBPal2c1 8935
#define BlckScrTilesCGBPal2c2 6596
#define BlckScrTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BlckScrTilesCGBPal3c0 6076
#define BlckScrTilesCGBPal3c1 8935
#define BlckScrTilesCGBPal3c2 6596
#define BlckScrTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BlckScrTilesCGBPal4c0 6076
#define BlckScrTilesCGBPal4c1 8935
#define BlckScrTilesCGBPal4c2 6596
#define BlckScrTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BlckScrTilesCGBPal5c0 6076
#define BlckScrTilesCGBPal5c1 8935
#define BlckScrTilesCGBPal5c2 6596
#define BlckScrTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BlckScrTilesCGBPal6c0 6076
#define BlckScrTilesCGBPal6c1 8935
#define BlckScrTilesCGBPal6c2 6596
#define BlckScrTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BlckScrTilesCGBPal7c0 6076
#define BlckScrTilesCGBPal7c1 8935
#define BlckScrTilesCGBPal7c2 6596
#define BlckScrTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char BlckScrTilesCGB[];
/* Start of tile array. */
extern const unsigned char BlckScrTiles[];

#endif

/* End of BLACKSCRTILES.H */
