//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Credits_H
#define METASPRITE_Credits_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Credits_TILE_ORIGIN 0
#define Credits_TILE_W 8
#define Credits_TILE_H 8
#define Credits_WIDTH 160
#define Credits_HEIGHT 144
#define Credits_TILE_COUNT 194
#define Credits_PALETTE_COUNT 1
#define Credits_COLORS_PER_PALETTE 4
#define Credits_TOTAL_COLORS 4
#define Credits_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Credits)

extern const palette_color_t Credits_palettes[4];
extern const uint8_t Credits_tiles[3104];

extern const unsigned char Credits_map[360];

#endif
