//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_HangerGG_H
#define METASPRITE_HangerGG_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define HangerGG_TILE_ORIGIN 0
#define HangerGG_TILE_W 8
#define HangerGG_TILE_H 8
#define HangerGG_WIDTH 160
#define HangerGG_HEIGHT 144
#define HangerGG_TILE_COUNT 253
#define HangerGG_PALETTE_COUNT 1
#define HangerGG_COLORS_PER_PALETTE 16
#define HangerGG_TOTAL_COLORS 16
#define HangerGG_MAP_ATTRIBUTES 0

BANKREF_EXTERN(HangerGG)

extern const palette_color_t HangerGG_palettes[16];
extern const uint8_t HangerGG_tiles[8096];

extern const unsigned char HangerGG_map[360];

#endif
