/*

 HELP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 20 x 18
   Tile set      : C:\gbdk\GBTD_GBMB_release\GBTD\RaptorMenuTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Help1_h_INCLUDE
#define __Help1_h_INCLUDE

#define Help1MapWidth 20
#define Help1MapHeight 18
#define Help1MapBank 1

#define Help1Map Help1MapPLN0
extern const void __bank_Help1MapPLN0;
extern const unsigned char Help1MapPLN0[];
extern const void __bank_Help1MapPLN01;
extern const unsigned char Help1MapPLN1[];

#endif

/* End of HELP1.H */
