#ifdef __TARGET_gb
//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Menu_H
#define METASPRITE_Menu_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Menu_TILE_ORIGIN 0
#define Menu_TILE_W 8
#define Menu_TILE_H 8
#define Menu_WIDTH 160
#define Menu_HEIGHT 144
#define Menu_TILE_COUNT 197
#define Menu_PALETTE_COUNT 1
#define Menu_COLORS_PER_PALETTE 4
#define Menu_TOTAL_COLORS 4
#define Menu_MAP_ATTRIBUTES Menu_map_attributes
#define Menu_MAP_ATTRIBUTES_WIDTH 20
#define Menu_MAP_ATTRIBUTES_HEIGHT 18
#define Menu_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define Menu_MAP_ATTRIBUTES_PACKED_HEIGHT 18

BANKREF_EXTERN(Menu)

extern const palette_color_t Menu_palettes[4];
extern const uint8_t Menu_tiles[3152];

extern const unsigned char Menu_map[360];
extern const unsigned char Menu_map_attributes[360];

#endif
#endif