#ifdef __TARGET_gg
//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_MenuGG_H
#define METASPRITE_MenuGG_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define MenuGG_TILE_ORIGIN 0
#define MenuGG_TILE_W 8
#define MenuGG_TILE_H 8
#define MenuGG_WIDTH 160
#define MenuGG_HEIGHT 144
#define MenuGG_TILE_COUNT 221
#define MenuGG_PALETTE_COUNT 1
#define MenuGG_COLORS_PER_PALETTE 16
#define MenuGG_TOTAL_COLORS 16
#define MenuGG_MAP_ATTRIBUTES 0

BANKREF_EXTERN(MenuGG)

extern const palette_color_t MenuGG_palettes[16];
extern const uint8_t MenuGG_tiles[7072];

extern const unsigned char MenuGG_map[360];

#endif
#endif