//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_raptor_full_H
#define METASPRITE_raptor_full_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define raptor_full_TILE_ORIGIN 0
#define raptor_full_TILE_W 8
#define raptor_full_TILE_H 16
#define raptor_full_WIDTH 160
#define raptor_full_HEIGHT 144
#define raptor_full_TILE_COUNT 286
#define raptor_full_PALETTE_COUNT 1
#define raptor_full_COLORS_PER_PALETTE 4
#define raptor_full_TOTAL_COLORS 4
#define raptor_full_PIVOT_X 80
#define raptor_full_PIVOT_Y 72
#define raptor_full_PIVOT_W 160
#define raptor_full_PIVOT_H 144

BANKREF_EXTERN(raptor_full)

extern const palette_color_t raptor_full_palettes[4];
extern const uint8_t raptor_full_tiles[4576];

extern const metasprite_t* const raptor_full_metasprites[1];

#endif
