/*

 SHOPTILES.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 46

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ShopTiles_h_INCLUDE
#define __ShopTiles_h_INCLUDE

/* Bank of tiles. */
#define ShopBank 0

/* Super Gameboy palette 0 */
#define ShopSGBPal0c0 6076
#define ShopSGBPal0c1 8935
#define ShopSGBPal0c2 6596
#define ShopSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ShopSGBPal1c0 6076
#define ShopSGBPal1c1 8935
#define ShopSGBPal1c2 6596
#define ShopSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ShopSGBPal2c0 6076
#define ShopSGBPal2c1 8935
#define ShopSGBPal2c2 6596
#define ShopSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ShopSGBPal3c0 6076
#define ShopSGBPal3c1 8935
#define ShopSGBPal3c2 6596
#define ShopSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ShopCGBPal0c0 24345
#define ShopCGBPal0c1 18004
#define ShopCGBPal0c2 13775
#define ShopCGBPal0c3 7434

/* Gameboy Color palette 1 */
#define ShopCGBPal1c0 24345
#define ShopCGBPal1c1 18004
#define ShopCGBPal1c2 13775
#define ShopCGBPal1c3 19

/* Gameboy Color palette 2 */
#define ShopCGBPal2c0 24345
#define ShopCGBPal2c1 18004
#define ShopCGBPal2c2 13775
#define ShopCGBPal2c3 1377

/* Gameboy Color palette 3 */
#define ShopCGBPal3c0 24345
#define ShopCGBPal3c1 18004
#define ShopCGBPal3c2 13775
#define ShopCGBPal3c3 21276

/* Gameboy Color palette 4 */
#define ShopCGBPal4c0 6076
#define ShopCGBPal4c1 8935
#define ShopCGBPal4c2 6596
#define ShopCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define ShopCGBPal5c0 6076
#define ShopCGBPal5c1 8935
#define ShopCGBPal5c2 6596
#define ShopCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define ShopCGBPal6c0 6076
#define ShopCGBPal6c1 8935
#define ShopCGBPal6c2 6596
#define ShopCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define ShopCGBPal7c0 6076
#define ShopCGBPal7c1 8935
#define ShopCGBPal7c2 6596
#define ShopCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char ShopCGB[];
extern const unsigned char ShopTLE0[];
extern const unsigned char ShopTLE1[];
extern const unsigned char ShopTLE2[];
extern const unsigned char ShopTLE3[];
extern const unsigned char ShopTLE4[];
extern const unsigned char ShopTLE5[];
extern const unsigned char ShopTLE6[];
extern const unsigned char ShopTLE7[];
extern const unsigned char ShopTLE8[];
extern const unsigned char ShopTLE9[];
extern const unsigned char ShopTLE10[];
extern const unsigned char ShopTLE11[];
extern const unsigned char ShopTLE12[];
extern const unsigned char ShopTLE13[];
extern const unsigned char ShopTLE14[];
extern const unsigned char ShopTLE15[];
extern const unsigned char ShopTLE16[];
extern const unsigned char ShopTLE17[];
extern const unsigned char ShopTLE18[];
extern const unsigned char ShopTLE19[];
extern const unsigned char ShopTLE20[];
extern const unsigned char ShopTLE21[];
extern const unsigned char ShopTLE22[];
extern const unsigned char ShopTLE23[];
extern const unsigned char ShopTLE24[];
extern const unsigned char ShopTLE25[];
extern const unsigned char ShopTLE26[];
extern const unsigned char ShopTLE27[];
extern const unsigned char ShopTLE28[];
extern const unsigned char ShopTLE29[];
extern const unsigned char ShopTLE30[];
extern const unsigned char ShopTLE31[];
extern const unsigned char ShopTLE32[];
extern const unsigned char ShopTLE33[];
extern const unsigned char ShopTLE34[];
extern const unsigned char ShopTLE35[];
extern const unsigned char ShopTLE36[];
extern const unsigned char ShopTLE37[];
extern const unsigned char ShopTLE38[];
extern const unsigned char ShopTLE39[];
extern const unsigned char ShopTLE40[];
extern const unsigned char ShopTLE41[];
extern const unsigned char ShopTLE42[];
extern const unsigned char ShopTLE43[];
extern const unsigned char ShopTLE44[];
extern const unsigned char ShopTLE45[];
extern const unsigned char ShopTLE46[];

#endif

/* End of SHOPTILES.H */
