/*

 SHOPTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 46

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ShopTiles_h_INCLUDE
#define __ShopTiles_h_INCLUDE

/* Bank of tiles. */
#define ShopBank 2

/* Super Gameboy palette 0 */
#define ShopSGBPal0c0 6076
#define ShopSGBPal0c1 8935
#define ShopSGBPal0c2 6596
#define ShopSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ShopSGBPal1c0 6076
#define ShopSGBPal1c1 8935
#define ShopSGBPal1c2 6596
#define ShopSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ShopSGBPal2c0 6076
#define ShopSGBPal2c1 8935
#define ShopSGBPal2c2 6596
#define ShopSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ShopSGBPal3c0 6076
#define ShopSGBPal3c1 8935
#define ShopSGBPal3c2 6596
#define ShopSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ShopCGBPal0c0 24345
#define ShopCGBPal0c1 18004
#define ShopCGBPal0c2 13775
#define ShopCGBPal0c3 7434

/* Gameboy Color palette 1 */
#define ShopCGBPal1c0 24345
#define ShopCGBPal1c1 18004
#define ShopCGBPal1c2 13775
#define ShopCGBPal1c3 19

/* Gameboy Color palette 2 */
#define ShopCGBPal2c0 24345
#define ShopCGBPal2c1 18004
#define ShopCGBPal2c2 13775
#define ShopCGBPal2c3 1377

/* Gameboy Color palette 3 */
#define ShopCGBPal3c0 24345
#define ShopCGBPal3c1 18004
#define ShopCGBPal3c2 13775
#define ShopCGBPal3c3 21276

/* Gameboy Color palette 4 */
#define ShopCGBPal4c0 6076
#define ShopCGBPal4c1 8935
#define ShopCGBPal4c2 6596
#define ShopCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define ShopCGBPal5c0 6076
#define ShopCGBPal5c1 8935
#define ShopCGBPal5c2 6596
#define ShopCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define ShopCGBPal6c0 6076
#define ShopCGBPal6c1 8935
#define ShopCGBPal6c2 6596
#define ShopCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define ShopCGBPal7c0 6076
#define ShopCGBPal7c1 8935
#define ShopCGBPal7c2 6596
#define ShopCGBPal7c3 5344
/* CGBpalette entries. */
extern const void __bank_ShopCGB;
extern const unsigned char ShopCGB[];
/* Start of tile array. */
extern const void __bank_Shop;
extern const unsigned char Shop[];

#endif

/* End of SHOPTILES.H */
