/*

 SHOP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 20 x 18
   Tile set      : C:\gbdk\GBTD_GBMB_release\GBTD\Shop.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Shop_h_INCLUDE
#define __Shop_h_INCLUDE

#define ShopScreenWidth 20
#define ShopScreenHeight 18
#define ShopScreenBank 1

#define ShopScreen ShopScreenPLN0
extern const void __bank_ShopScreenPLN0;
extern const unsigned char ShopScreenPLN0[];
extern const void __bank_ShopScreenPLN01;
extern const unsigned char ShopScreenPLN1[];

#endif

/* End of SHOP.H */
