/*

 SHOPTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 46

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ShopTiles_h_INCLUDE
#define __ShopTiles_h_INCLUDE

/* Bank of tiles. */
#define ShopTilesBank 2

/* Super Gameboy palette 0 */
#define ShopTilesSGBPal0c0 6076
#define ShopTilesSGBPal0c1 8935
#define ShopTilesSGBPal0c2 6596
#define ShopTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ShopTilesSGBPal1c0 6076
#define ShopTilesSGBPal1c1 8935
#define ShopTilesSGBPal1c2 6596
#define ShopTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ShopTilesSGBPal2c0 6076
#define ShopTilesSGBPal2c1 8935
#define ShopTilesSGBPal2c2 6596
#define ShopTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ShopTilesSGBPal3c0 6076
#define ShopTilesSGBPal3c1 8935
#define ShopTilesSGBPal3c2 6596
#define ShopTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ShopTilesCGBPal0c0 24345
#define ShopTilesCGBPal0c1 18004
#define ShopTilesCGBPal0c2 13775
#define ShopTilesCGBPal0c3 7434

/* Gameboy Color palette 1 */
#define ShopTilesCGBPal1c0 24345
#define ShopTilesCGBPal1c1 18004
#define ShopTilesCGBPal1c2 13775
#define ShopTilesCGBPal1c3 19

/* Gameboy Color palette 2 */
#define ShopTilesCGBPal2c0 24345
#define ShopTilesCGBPal2c1 18004
#define ShopTilesCGBPal2c2 13775
#define ShopTilesCGBPal2c3 1377

/* Gameboy Color palette 3 */
#define ShopTilesCGBPal3c0 24345
#define ShopTilesCGBPal3c1 18004
#define ShopTilesCGBPal3c2 13775
#define ShopTilesCGBPal3c3 21276

/* Gameboy Color palette 4 */
#define ShopTilesCGBPal4c0 6076
#define ShopTilesCGBPal4c1 8935
#define ShopTilesCGBPal4c2 6596
#define ShopTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define ShopTilesCGBPal5c0 6076
#define ShopTilesCGBPal5c1 8935
#define ShopTilesCGBPal5c2 6596
#define ShopTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define ShopTilesCGBPal6c0 6076
#define ShopTilesCGBPal6c1 8935
#define ShopTilesCGBPal6c2 6596
#define ShopTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define ShopTilesCGBPal7c0 6076
#define ShopTilesCGBPal7c1 8935
#define ShopTilesCGBPal7c2 6596
#define ShopTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const void __bank_ShopTilesCGB;
extern const unsigned char ShopTilesCGB[];
/* Start of tile array. */
extern const void __bank_ShopTiles;
extern const unsigned char ShopTiles[];

#endif

/* End of SHOPTILES.H */
