//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_TitleGG_H
#define METASPRITE_TitleGG_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define TitleGG_TILE_ORIGIN 0
#define TitleGG_TILE_W 8
#define TitleGG_TILE_H 8
#define TitleGG_WIDTH 160
#define TitleGG_HEIGHT 144
#define TitleGG_TILE_COUNT 233
#define TitleGG_PALETTE_COUNT 1
#define TitleGG_COLORS_PER_PALETTE 16
#define TitleGG_TOTAL_COLORS 16
#define TitleGG_MAP_ATTRIBUTES 0

BANKREF_EXTERN(TitleGG)

extern const palette_color_t TitleGG_palettes[16];
extern const uint8_t TitleGG_tiles[7456];

extern const unsigned char TitleGG_map[360];

#endif
