//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Intro_H
#define METASPRITE_Intro_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Intro_TILE_ORIGIN 0
#define Intro_TILE_W 8
#define Intro_TILE_H 8
#define Intro_WIDTH 160
#define Intro_HEIGHT 144
#define Intro_TILE_COUNT 232
#define Intro_PALETTE_COUNT 1
#define Intro_COLORS_PER_PALETTE 4
#define Intro_TOTAL_COLORS 4
#define Intro_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Intro)

extern const palette_color_t Intro_palettes[4];
extern const uint8_t Intro_tiles[3712];

extern const unsigned char Intro_map[360];

#endif
