//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_SGBBack_H
#define METASPRITE_SGBBack_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define SGBBack_TILE_ORIGIN 0
#define SGBBack_TILE_W 8
#define SGBBack_TILE_H 8
#define SGBBack_WIDTH 256
#define SGBBack_HEIGHT 224
#define SGBBack_TILE_COUNT 230
#define SGBBack_PALETTE_COUNT 1
#define SGBBack_COLORS_PER_PALETTE 16
#define SGBBack_TOTAL_COLORS 16
#define SGBBack_MAP_ATTRIBUTES 0
#define SGBBack_MAP_ATTRIBUTES_WIDTH 32
#define SGBBack_MAP_ATTRIBUTES_HEIGHT 28
#define SGBBack_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define SGBBack_MAP_ATTRIBUTES_PACKED_HEIGHT 28

BANKREF_EXTERN(SGBBack)

extern const palette_color_t SGBBack_palettes[16];
extern const uint8_t SGBBack_tiles[7360];

extern const unsigned char SGBBack_map[1792];

#endif
