//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_BravoW1TilesGG_H
#define METASPRITE_BravoW1TilesGG_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define BravoW1TilesGG_TILE_ORIGIN 0
#define BravoW1TilesGG_TILE_W 8
#define BravoW1TilesGG_TILE_H 8
#define BravoW1TilesGG_WIDTH 128
#define BravoW1TilesGG_HEIGHT 96
#define BravoW1TilesGG_TILE_COUNT 134
#define BravoW1TilesGG_PALETTE_COUNT 1
#define BravoW1TilesGG_COLORS_PER_PALETTE 16
#define BravoW1TilesGG_TOTAL_COLORS 16

BANKREF_EXTERN(BravoW1TilesGG)

extern const palette_color_t BravoW1TilesGG_palettes[16];
extern const uint8_t BravoW1TilesGG_tiles[4288];


#endif
