//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_BravoW1TilesSMS_H
#define METASPRITE_BravoW1TilesSMS_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define BravoW1TilesSMS_TILE_ORIGIN 0
#define BravoW1TilesSMS_TILE_W 8
#define BravoW1TilesSMS_TILE_H 8
#define BravoW1TilesSMS_WIDTH 128
#define BravoW1TilesSMS_HEIGHT 96
#define BravoW1TilesSMS_TILE_COUNT 134
#define BravoW1TilesSMS_PALETTE_COUNT 1
#define BravoW1TilesSMS_COLORS_PER_PALETTE 16
#define BravoW1TilesSMS_TOTAL_COLORS 16

BANKREF_EXTERN(BravoW1TilesSMS)

extern const palette_color_t BravoW1TilesSMS_palettes[16];
extern const uint8_t BravoW1TilesSMS_tiles[4288];


#endif
