/*

 BRAVOW1TILESVBANK1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __BravoW1TilesVBank1_h_INCLUDE
#define __BravoW1TilesVBank1_h_INCLUDE

/* Bank of tiles. */
#define Bravo1MapTilesVBank1Bank 5

/* Super Gameboy palette 0 */
#define Bravo1MapTilesVBank1SGBPal0c0 6076
#define Bravo1MapTilesVBank1SGBPal0c1 8935
#define Bravo1MapTilesVBank1SGBPal0c2 6596
#define Bravo1MapTilesVBank1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Bravo1MapTilesVBank1SGBPal1c0 6076
#define Bravo1MapTilesVBank1SGBPal1c1 8935
#define Bravo1MapTilesVBank1SGBPal1c2 6596
#define Bravo1MapTilesVBank1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Bravo1MapTilesVBank1SGBPal2c0 6076
#define Bravo1MapTilesVBank1SGBPal2c1 8935
#define Bravo1MapTilesVBank1SGBPal2c2 6596
#define Bravo1MapTilesVBank1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Bravo1MapTilesVBank1SGBPal3c0 6076
#define Bravo1MapTilesVBank1SGBPal3c1 8935
#define Bravo1MapTilesVBank1SGBPal3c2 6596
#define Bravo1MapTilesVBank1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Bravo1MapTilesVBank1CGBPal0c0 16640
#define Bravo1MapTilesVBank1CGBPal0c1 3423
#define Bravo1MapTilesVBank1CGBPal0c2 10570
#define Bravo1MapTilesVBank1CGBPal0c3 4228

/* Gameboy Color palette 1 */
#define Bravo1MapTilesVBank1CGBPal1c0 32264
#define Bravo1MapTilesVBank1CGBPal1c1 16640
#define Bravo1MapTilesVBank1CGBPal1c2 202
#define Bravo1MapTilesVBank1CGBPal1c3 1446

/* Gameboy Color palette 2 */
#define Bravo1MapTilesVBank1CGBPal2c0 32264
#define Bravo1MapTilesVBank1CGBPal2c1 16640
#define Bravo1MapTilesVBank1CGBPal2c2 12512
#define Bravo1MapTilesVBank1CGBPal2c3 202

/* Gameboy Color palette 3 */
#define Bravo1MapTilesVBank1CGBPal3c0 15857
#define Bravo1MapTilesVBank1CGBPal3c1 16640
#define Bravo1MapTilesVBank1CGBPal3c2 206
#define Bravo1MapTilesVBank1CGBPal3c3 202

/* Gameboy Color palette 4 */
#define Bravo1MapTilesVBank1CGBPal4c0 15857
#define Bravo1MapTilesVBank1CGBPal4c1 8458
#define Bravo1MapTilesVBank1CGBPal4c2 202
#define Bravo1MapTilesVBank1CGBPal4c3 68

/* Gameboy Color palette 5 */
#define Bravo1MapTilesVBank1CGBPal5c0 19028
#define Bravo1MapTilesVBank1CGBPal5c1 15857
#define Bravo1MapTilesVBank1CGBPal5c2 11629
#define Bravo1MapTilesVBank1CGBPal5c3 7401

/* Gameboy Color palette 6 */
#define Bravo1MapTilesVBank1CGBPal6c0 1577
#define Bravo1MapTilesVBank1CGBPal6c1 1446
#define Bravo1MapTilesVBank1CGBPal6c2 202
#define Bravo1MapTilesVBank1CGBPal6c3 1348

/* Gameboy Color palette 7 */
#define Bravo1MapTilesVBank1CGBPal7c0 32767
#define Bravo1MapTilesVBank1CGBPal7c1 799
#define Bravo1MapTilesVBank1CGBPal7c2 502
#define Bravo1MapTilesVBank1CGBPal7c3 4228
/* CGBpalette entries. */
extern const void __bank_Bravo1MapTilesVBank1CGB;
extern const unsigned char Bravo1MapTilesVBank1CGB[];
/* Start of tile array. */
extern const void __bank_Bravo1MapTilesVBank1;
extern const unsigned char Bravo1MapTilesVBank1[];

#endif

/* End of BRAVOW1TILESVBANK1.H */
