/*

 BRAVOW1TILESSGB.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __BravoW1TilesSGB_h_INCLUDE
#define __BravoW1TilesSGB_h_INCLUDE

/* Bank of tiles. */
#define Bravo1MapTilesSGBBank 3

/* Super Gameboy palette 0 */
#define Bravo1MapTilesSGBSGBPal0c0 6076
#define Bravo1MapTilesSGBSGBPal0c1 8935
#define Bravo1MapTilesSGBSGBPal0c2 6596
#define Bravo1MapTilesSGBSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Bravo1MapTilesSGBSGBPal1c0 6076
#define Bravo1MapTilesSGBSGBPal1c1 8935
#define Bravo1MapTilesSGBSGBPal1c2 6596
#define Bravo1MapTilesSGBSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Bravo1MapTilesSGBSGBPal2c0 6076
#define Bravo1MapTilesSGBSGBPal2c1 8935
#define Bravo1MapTilesSGBSGBPal2c2 6596
#define Bravo1MapTilesSGBSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Bravo1MapTilesSGBSGBPal3c0 6076
#define Bravo1MapTilesSGBSGBPal3c1 8935
#define Bravo1MapTilesSGBSGBPal3c2 6596
#define Bravo1MapTilesSGBSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Bravo1MapTilesSGBCGBPal0c0 16640
#define Bravo1MapTilesSGBCGBPal0c1 3423
#define Bravo1MapTilesSGBCGBPal0c2 10570
#define Bravo1MapTilesSGBCGBPal0c3 4228

/* Gameboy Color palette 1 */
#define Bravo1MapTilesSGBCGBPal1c0 32264
#define Bravo1MapTilesSGBCGBPal1c1 16640
#define Bravo1MapTilesSGBCGBPal1c2 202
#define Bravo1MapTilesSGBCGBPal1c3 1446

/* Gameboy Color palette 2 */
#define Bravo1MapTilesSGBCGBPal2c0 32264
#define Bravo1MapTilesSGBCGBPal2c1 16640
#define Bravo1MapTilesSGBCGBPal2c2 12512
#define Bravo1MapTilesSGBCGBPal2c3 202

/* Gameboy Color palette 3 */
#define Bravo1MapTilesSGBCGBPal3c0 15857
#define Bravo1MapTilesSGBCGBPal3c1 16640
#define Bravo1MapTilesSGBCGBPal3c2 206
#define Bravo1MapTilesSGBCGBPal3c3 202

/* Gameboy Color palette 4 */
#define Bravo1MapTilesSGBCGBPal4c0 15857
#define Bravo1MapTilesSGBCGBPal4c1 8458
#define Bravo1MapTilesSGBCGBPal4c2 202
#define Bravo1MapTilesSGBCGBPal4c3 68

/* Gameboy Color palette 5 */
#define Bravo1MapTilesSGBCGBPal5c0 19028
#define Bravo1MapTilesSGBCGBPal5c1 15857
#define Bravo1MapTilesSGBCGBPal5c2 11629
#define Bravo1MapTilesSGBCGBPal5c3 7401

/* Gameboy Color palette 6 */
#define Bravo1MapTilesSGBCGBPal6c0 1577
#define Bravo1MapTilesSGBCGBPal6c1 1446
#define Bravo1MapTilesSGBCGBPal6c2 202
#define Bravo1MapTilesSGBCGBPal6c3 1348

/* Gameboy Color palette 7 */
#define Bravo1MapTilesSGBCGBPal7c0 32767
#define Bravo1MapTilesSGBCGBPal7c1 799
#define Bravo1MapTilesSGBCGBPal7c2 502
#define Bravo1MapTilesSGBCGBPal7c3 4228
/* CGBpalette entries. */
extern const void __bank_Bravo1MapTilesSGBCGB;
extern const unsigned char Bravo1MapTilesSGBCGB[];
/* Start of tile array. */
extern const void __bank_Bravo1MapTilesSGB;
extern const unsigned char Bravo1MapTilesSGB[];

#endif

/* End of BRAVOW1TILESSGB.H */
