/*

 BRAVOW1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 6
   Map size      : 20 x 255
   Tile set      : C:\gbdk\GBTD_GBMB_release\GBTD\BravoW1BGTilesSGB.gbr
   Plane count   : 3 planes (24 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BravoW1Map_h_INCLUDE
#define __BravoW1Map_h_INCLUDE

#define BravoWave1Width 20
#define BravoWave1Height 255
#define BravoWave1Bank 5

#define BravoWave1 BravoWave1PLN0
extern const void __bank_BravoWave1PLN0;
extern const unsigned char BravoWave1PLN0[];
extern const void __bank_BravoWave1PLN01;
extern const unsigned char BravoWave1PLN1[];
extern const void __bank_BravoWave1PLN02;
extern const unsigned char BravoWave1PLN2[];

#endif

/* End of BRAVOW1MAP.H */
