/*

 BRAVOW1TILESMAIN.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 101

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __BravoW1TilesMain_h_INCLUDE
#define __BravoW1TilesMain_h_INCLUDE

/* Bank of tiles. */
#define Bravo1MapTilesMainBank 3

/* Super Gameboy palette 0 */
#define Bravo1MapTilesMainSGBPal0c0 6076
#define Bravo1MapTilesMainSGBPal0c1 8935
#define Bravo1MapTilesMainSGBPal0c2 6596
#define Bravo1MapTilesMainSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Bravo1MapTilesMainSGBPal1c0 6076
#define Bravo1MapTilesMainSGBPal1c1 8935
#define Bravo1MapTilesMainSGBPal1c2 6596
#define Bravo1MapTilesMainSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Bravo1MapTilesMainSGBPal2c0 6076
#define Bravo1MapTilesMainSGBPal2c1 8935
#define Bravo1MapTilesMainSGBPal2c2 6596
#define Bravo1MapTilesMainSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Bravo1MapTilesMainSGBPal3c0 6076
#define Bravo1MapTilesMainSGBPal3c1 8935
#define Bravo1MapTilesMainSGBPal3c2 6596
#define Bravo1MapTilesMainSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Bravo1MapTilesMainCGBPal0c0 16640
#define Bravo1MapTilesMainCGBPal0c1 3423
#define Bravo1MapTilesMainCGBPal0c2 10570
#define Bravo1MapTilesMainCGBPal0c3 4228

/* Gameboy Color palette 1 */
#define Bravo1MapTilesMainCGBPal1c0 32264
#define Bravo1MapTilesMainCGBPal1c1 16640
#define Bravo1MapTilesMainCGBPal1c2 202
#define Bravo1MapTilesMainCGBPal1c3 1446

/* Gameboy Color palette 2 */
#define Bravo1MapTilesMainCGBPal2c0 32264
#define Bravo1MapTilesMainCGBPal2c1 16640
#define Bravo1MapTilesMainCGBPal2c2 12512
#define Bravo1MapTilesMainCGBPal2c3 202

/* Gameboy Color palette 3 */
#define Bravo1MapTilesMainCGBPal3c0 15857
#define Bravo1MapTilesMainCGBPal3c1 16640
#define Bravo1MapTilesMainCGBPal3c2 206
#define Bravo1MapTilesMainCGBPal3c3 202

/* Gameboy Color palette 4 */
#define Bravo1MapTilesMainCGBPal4c0 15857
#define Bravo1MapTilesMainCGBPal4c1 8458
#define Bravo1MapTilesMainCGBPal4c2 202
#define Bravo1MapTilesMainCGBPal4c3 68

/* Gameboy Color palette 5 */
#define Bravo1MapTilesMainCGBPal5c0 19028
#define Bravo1MapTilesMainCGBPal5c1 15857
#define Bravo1MapTilesMainCGBPal5c2 11629
#define Bravo1MapTilesMainCGBPal5c3 7401

/* Gameboy Color palette 6 */
#define Bravo1MapTilesMainCGBPal6c0 1577
#define Bravo1MapTilesMainCGBPal6c1 1446
#define Bravo1MapTilesMainCGBPal6c2 202
#define Bravo1MapTilesMainCGBPal6c3 1348

/* Gameboy Color palette 7 */
#define Bravo1MapTilesMainCGBPal7c0 32767
#define Bravo1MapTilesMainCGBPal7c1 799
#define Bravo1MapTilesMainCGBPal7c2 502
#define Bravo1MapTilesMainCGBPal7c3 4228
/* CGBpalette entries. */
extern const void __bank_Bravo1MapTilesMainCGB;
extern const unsigned char Bravo1MapTilesMainCGB[];
/* Start of tile array. */
extern const void __bank_Bravo1MapTilesMain;
extern const unsigned char Bravo1MapTilesMain[];

#endif

/* End of BRAVOW1TILESMAIN.H */
