/*

 BRAVOW1GBC.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 20 x 255
   Tile set      : C:\gbdk\GBTD_GBMB_release\GBTD\Bravo1BGTilesGBC.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BravoW1GBC_h_INCLUDE
#define __BravoW1GBC_h_INCLUDE

#define BravoWave1Width 20
#define BravoWave1Height 255
#define BravoWave1Bank 3

#define BravoWave1 BravoWave1PLN0
extern const void __bank_BravoWave1PLN0;
extern const unsigned char BravoWave1PLN0[];
extern const void __bank_BravoWave1PLN01;
extern const unsigned char BravoWave1PLN1[];

#endif

/* End of BRAVOW1GBC.H */
