/*

 BRAVO1TILESGBC.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 52

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Bravo1TilesGBC_h_INCLUDE
#define __Bravo1TilesGBC_h_INCLUDE

/* Bank of tiles. */
#define Bravo1MapTilesBank 2

/* Super Gameboy palette 0 */
#define Bravo1MapTilesSGBPal0c0 6076
#define Bravo1MapTilesSGBPal0c1 8935
#define Bravo1MapTilesSGBPal0c2 6596
#define Bravo1MapTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Bravo1MapTilesSGBPal1c0 6076
#define Bravo1MapTilesSGBPal1c1 8935
#define Bravo1MapTilesSGBPal1c2 6596
#define Bravo1MapTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Bravo1MapTilesSGBPal2c0 6076
#define Bravo1MapTilesSGBPal2c1 8935
#define Bravo1MapTilesSGBPal2c2 6596
#define Bravo1MapTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Bravo1MapTilesSGBPal3c0 6076
#define Bravo1MapTilesSGBPal3c1 8935
#define Bravo1MapTilesSGBPal3c2 6596
#define Bravo1MapTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Bravo1MapTilesCGBPal0c0 12953
#define Bravo1MapTilesCGBPal0c1 9716
#define Bravo1MapTilesCGBPal0c2 6479
#define Bravo1MapTilesCGBPal0c3 3242

/* Gameboy Color palette 1 */
#define Bravo1MapTilesCGBPal1c0 32264
#define Bravo1MapTilesCGBPal1c1 16640
#define Bravo1MapTilesCGBPal1c2 202
#define Bravo1MapTilesCGBPal1c3 1446

/* Gameboy Color palette 2 */
#define Bravo1MapTilesCGBPal2c0 32264
#define Bravo1MapTilesCGBPal2c1 16640
#define Bravo1MapTilesCGBPal2c2 12512
#define Bravo1MapTilesCGBPal2c3 202

/* Gameboy Color palette 3 */
#define Bravo1MapTilesCGBPal3c0 15857
#define Bravo1MapTilesCGBPal3c1 16640
#define Bravo1MapTilesCGBPal3c2 206
#define Bravo1MapTilesCGBPal3c3 202

/* Gameboy Color palette 4 */
#define Bravo1MapTilesCGBPal4c0 15857
#define Bravo1MapTilesCGBPal4c1 8458
#define Bravo1MapTilesCGBPal4c2 202
#define Bravo1MapTilesCGBPal4c3 68

/* Gameboy Color palette 5 */
#define Bravo1MapTilesCGBPal5c0 6076
#define Bravo1MapTilesCGBPal5c1 8935
#define Bravo1MapTilesCGBPal5c2 6596
#define Bravo1MapTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define Bravo1MapTilesCGBPal6c0 6076
#define Bravo1MapTilesCGBPal6c1 8935
#define Bravo1MapTilesCGBPal6c2 6596
#define Bravo1MapTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define Bravo1MapTilesCGBPal7c0 32767
#define Bravo1MapTilesCGBPal7c1 799
#define Bravo1MapTilesCGBPal7c2 502
#define Bravo1MapTilesCGBPal7c3 4228
/* CGBpalette entries. */
extern const void __bank_Bravo1MapTilesCGB;
extern const unsigned char Bravo1MapTilesCGB[];
/* Start of tile array. */
extern const void __bank_Bravo1MapTiles;
extern const unsigned char Bravo1MapTiles[];

#endif

/* End of BRAVO1TILESGBC.H */
