/*

 BRAVOW1TILESSECOND.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __BravoW1TilesSecond_h_INCLUDE
#define __BravoW1TilesSecond_h_INCLUDE

/* Bank of tiles. */
#define Bravo1MapTilesSecondBank 3

/* Super Gameboy palette 0 */
#define Bravo1MapTilesSecondSGBPal0c0 6076
#define Bravo1MapTilesSecondSGBPal0c1 8935
#define Bravo1MapTilesSecondSGBPal0c2 6596
#define Bravo1MapTilesSecondSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Bravo1MapTilesSecondSGBPal1c0 6076
#define Bravo1MapTilesSecondSGBPal1c1 8935
#define Bravo1MapTilesSecondSGBPal1c2 6596
#define Bravo1MapTilesSecondSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Bravo1MapTilesSecondSGBPal2c0 6076
#define Bravo1MapTilesSecondSGBPal2c1 8935
#define Bravo1MapTilesSecondSGBPal2c2 6596
#define Bravo1MapTilesSecondSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Bravo1MapTilesSecondSGBPal3c0 6076
#define Bravo1MapTilesSecondSGBPal3c1 8935
#define Bravo1MapTilesSecondSGBPal3c2 6596
#define Bravo1MapTilesSecondSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Bravo1MapTilesSecondCGBPal0c0 16640
#define Bravo1MapTilesSecondCGBPal0c1 3423
#define Bravo1MapTilesSecondCGBPal0c2 10570
#define Bravo1MapTilesSecondCGBPal0c3 4228

/* Gameboy Color palette 1 */
#define Bravo1MapTilesSecondCGBPal1c0 32264
#define Bravo1MapTilesSecondCGBPal1c1 16640
#define Bravo1MapTilesSecondCGBPal1c2 202
#define Bravo1MapTilesSecondCGBPal1c3 1446

/* Gameboy Color palette 2 */
#define Bravo1MapTilesSecondCGBPal2c0 32264
#define Bravo1MapTilesSecondCGBPal2c1 16640
#define Bravo1MapTilesSecondCGBPal2c2 12512
#define Bravo1MapTilesSecondCGBPal2c3 202

/* Gameboy Color palette 3 */
#define Bravo1MapTilesSecondCGBPal3c0 15857
#define Bravo1MapTilesSecondCGBPal3c1 16640
#define Bravo1MapTilesSecondCGBPal3c2 206
#define Bravo1MapTilesSecondCGBPal3c3 202

/* Gameboy Color palette 4 */
#define Bravo1MapTilesSecondCGBPal4c0 15857
#define Bravo1MapTilesSecondCGBPal4c1 8458
#define Bravo1MapTilesSecondCGBPal4c2 202
#define Bravo1MapTilesSecondCGBPal4c3 68

/* Gameboy Color palette 5 */
#define Bravo1MapTilesSecondCGBPal5c0 19028
#define Bravo1MapTilesSecondCGBPal5c1 15857
#define Bravo1MapTilesSecondCGBPal5c2 11629
#define Bravo1MapTilesSecondCGBPal5c3 7401

/* Gameboy Color palette 6 */
#define Bravo1MapTilesSecondCGBPal6c0 1577
#define Bravo1MapTilesSecondCGBPal6c1 1446
#define Bravo1MapTilesSecondCGBPal6c2 202
#define Bravo1MapTilesSecondCGBPal6c3 1348

/* Gameboy Color palette 7 */
#define Bravo1MapTilesSecondCGBPal7c0 32767
#define Bravo1MapTilesSecondCGBPal7c1 799
#define Bravo1MapTilesSecondCGBPal7c2 502
#define Bravo1MapTilesSecondCGBPal7c3 4228
/* CGBpalette entries. */
extern const void __bank_Bravo1MapTilesSecondCGB;
extern const unsigned char Bravo1MapTilesSecondCGB[];
/* Start of tile array. */
extern const void __bank_Bravo1MapTilesSecond;
extern const unsigned char Bravo1MapTilesSecond[];

#endif

/* End of BRAVOW1TILESSECOND.H */
