/*

 RAPTORMAPTILESGBSC.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 51

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __RaptorMapTilesGBSC_h_INCLUDE
#define __RaptorMapTilesGBSC_h_INCLUDE

/* Bank of tiles. */
#define RaptorMapTilesBank 0

/* Super Gameboy palette 0 */
#define RaptorMapTilesSGBPal0c0 6076
#define RaptorMapTilesSGBPal0c1 8935
#define RaptorMapTilesSGBPal0c2 6596
#define RaptorMapTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define RaptorMapTilesSGBPal1c0 6076
#define RaptorMapTilesSGBPal1c1 8935
#define RaptorMapTilesSGBPal1c2 6596
#define RaptorMapTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define RaptorMapTilesSGBPal2c0 6076
#define RaptorMapTilesSGBPal2c1 8935
#define RaptorMapTilesSGBPal2c2 6596
#define RaptorMapTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define RaptorMapTilesSGBPal3c0 6076
#define RaptorMapTilesSGBPal3c1 8935
#define RaptorMapTilesSGBPal3c2 6596
#define RaptorMapTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define RaptorMapTilesCGBPal0c0 12953
#define RaptorMapTilesCGBPal0c1 9716
#define RaptorMapTilesCGBPal0c2 6479
#define RaptorMapTilesCGBPal0c3 3242

/* Gameboy Color palette 1 */
#define RaptorMapTilesCGBPal1c0 32264
#define RaptorMapTilesCGBPal1c1 16640
#define RaptorMapTilesCGBPal1c2 202
#define RaptorMapTilesCGBPal1c3 1446

/* Gameboy Color palette 2 */
#define RaptorMapTilesCGBPal2c0 32264
#define RaptorMapTilesCGBPal2c1 16640
#define RaptorMapTilesCGBPal2c2 12512
#define RaptorMapTilesCGBPal2c3 202

/* Gameboy Color palette 3 */
#define RaptorMapTilesCGBPal3c0 15857
#define RaptorMapTilesCGBPal3c1 16640
#define RaptorMapTilesCGBPal3c2 12512
#define RaptorMapTilesCGBPal3c3 206

/* Gameboy Color palette 4 */
#define RaptorMapTilesCGBPal4c0 6076
#define RaptorMapTilesCGBPal4c1 8935
#define RaptorMapTilesCGBPal4c2 6596
#define RaptorMapTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define RaptorMapTilesCGBPal5c0 6076
#define RaptorMapTilesCGBPal5c1 8935
#define RaptorMapTilesCGBPal5c2 6596
#define RaptorMapTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define RaptorMapTilesCGBPal6c0 6076
#define RaptorMapTilesCGBPal6c1 8935
#define RaptorMapTilesCGBPal6c2 6596
#define RaptorMapTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define RaptorMapTilesCGBPal7c0 32767
#define RaptorMapTilesCGBPal7c1 799
#define RaptorMapTilesCGBPal7c2 502
#define RaptorMapTilesCGBPal7c3 4228
/* CGBpalette entries. */
extern const unsigned char RaptorMapTilesCGB[];
/* Start of tile array. */
extern const unsigned char RaptorMapTiles[];

#endif

/* End of RAPTORMAPTILESGBSC.H */
