/*

 RAPTORMAPTILESGBC.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 51

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __RaptorMapTilesGBC_h_INCLUDE
#define __RaptorMapTilesGBC_h_INCLUDE

/* Bank of tiles. */
#define RaptorMapTilesBank 0

/* Super Gameboy palette 0 */
#define RaptorMapTilesSGBPal0c0 6076
#define RaptorMapTilesSGBPal0c1 8935
#define RaptorMapTilesSGBPal0c2 6596
#define RaptorMapTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define RaptorMapTilesSGBPal1c0 6076
#define RaptorMapTilesSGBPal1c1 8935
#define RaptorMapTilesSGBPal1c2 6596
#define RaptorMapTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define RaptorMapTilesSGBPal2c0 6076
#define RaptorMapTilesSGBPal2c1 8935
#define RaptorMapTilesSGBPal2c2 6596
#define RaptorMapTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define RaptorMapTilesSGBPal3c0 6076
#define RaptorMapTilesSGBPal3c1 8935
#define RaptorMapTilesSGBPal3c2 6596
#define RaptorMapTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define RaptorMapTilesCGBPal0c0 6076
#define RaptorMapTilesCGBPal0c1 8935
#define RaptorMapTilesCGBPal0c2 6596
#define RaptorMapTilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define RaptorMapTilesCGBPal1c0 29652
#define RaptorMapTilesCGBPal1c1 32072
#define RaptorMapTilesCGBPal1c2 1262
#define RaptorMapTilesCGBPal1c3 1441

/* Gameboy Color palette 2 */
#define RaptorMapTilesCGBPal2c0 29652
#define RaptorMapTilesCGBPal2c1 32072
#define RaptorMapTilesCGBPal2c2 23648
#define RaptorMapTilesCGBPal2c3 1262

/* Gameboy Color palette 3 */
#define RaptorMapTilesCGBPal3c0 21140
#define RaptorMapTilesCGBPal3c1 32072
#define RaptorMapTilesCGBPal3c2 23648
#define RaptorMapTilesCGBPal3c3 1262

/* Gameboy Color palette 4 */
#define RaptorMapTilesCGBPal4c0 6076
#define RaptorMapTilesCGBPal4c1 8935
#define RaptorMapTilesCGBPal4c2 6596
#define RaptorMapTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define RaptorMapTilesCGBPal5c0 6076
#define RaptorMapTilesCGBPal5c1 8935
#define RaptorMapTilesCGBPal5c2 6596
#define RaptorMapTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define RaptorMapTilesCGBPal6c0 6076
#define RaptorMapTilesCGBPal6c1 8935
#define RaptorMapTilesCGBPal6c2 6596
#define RaptorMapTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define RaptorMapTilesCGBPal7c0 6076
#define RaptorMapTilesCGBPal7c1 8935
#define RaptorMapTilesCGBPal7c2 6596
#define RaptorMapTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char RaptorMapTilesCGB[];
/* Start of tile array. */
extern const unsigned char RaptorMapTiles[];

#endif

/* End of RAPTORMAPTILESGBC.H */
