/*

 SIMPLEBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : F:\RetroDev\gbdk\GBTD\Sprites\Background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __SimpleBackground_h_INCLUDE
#define __SimpleBackground_h_INCLUDE

#define SimpleBackgroundWidth 40
#define SimpleBackgroundHeight 18
#define SimpleBackgroundBank 0

extern const unsigned char SimpleBackground[];

#endif

/* End of SIMPLEBACKGROUND.H */
