/*

 RAPTORWINDOW.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\gbdk\GBTD_GBMB_release\GBTD\RaptorDialogTilesV2.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __RaptorWindow_h_INCLUDE
#define __RaptorWindow_h_INCLUDE

#define RaptorWindowWidth 20
#define RaptorWindowHeight 2
#define RaptorWindowBank 0

#define RaptorWindow RaptorWindowPLN0
extern const unsigned char RaptorWindowPLN0[];
extern const unsigned char RaptorWindowPLN1[];

#endif

/* End of RAPTORWINDOW.H */
