/*

 RAPTORDIALOGTILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
const unsigned char RaptorDialogCGB[] =
{
  0x01
};
/* Start of tile array. */
const unsigned char RaptorDialog[] =
{
  0x38,0x38,0x44,0x54,0x82,0x92,0x60,0x70,
  0x0C,0x1C,0x82,0x92,0x44,0x54,0x38,0x38
};

/* End of RAPTORDIALOGTILES.C */
