/*

 RAPTORDIALOGTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 102 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __RaptorDialogTiles_h_INCLUDE
#define __RaptorDialogTiles_h_INCLUDE

/* Bank of tiles. */
#define RaptorDialogBank 0

/* Super Gameboy palette 0 */
#define RaptorDialogSGBPal0c0 6076
#define RaptorDialogSGBPal0c1 8935
#define RaptorDialogSGBPal0c2 6596
#define RaptorDialogSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define RaptorDialogSGBPal1c0 6076
#define RaptorDialogSGBPal1c1 8935
#define RaptorDialogSGBPal1c2 6596
#define RaptorDialogSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define RaptorDialogSGBPal2c0 6076
#define RaptorDialogSGBPal2c1 8935
#define RaptorDialogSGBPal2c2 6596
#define RaptorDialogSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define RaptorDialogSGBPal3c0 6076
#define RaptorDialogSGBPal3c1 8935
#define RaptorDialogSGBPal3c2 6596
#define RaptorDialogSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define RaptorDialogCGBPal0c0 6076
#define RaptorDialogCGBPal0c1 8935
#define RaptorDialogCGBPal0c2 6596
#define RaptorDialogCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define RaptorDialogCGBPal1c0 32767
#define RaptorDialogCGBPal1c1 32767
#define RaptorDialogCGBPal1c2 639
#define RaptorDialogCGBPal1c3 471

/* Gameboy Color palette 2 */
#define RaptorDialogCGBPal2c0 32767
#define RaptorDialogCGBPal2c1 19352
#define RaptorDialogCGBPal2c2 18067
#define RaptorDialogCGBPal2c3 5611

/* Gameboy Color palette 3 */
#define RaptorDialogCGBPal3c0 32767
#define RaptorDialogCGBPal3c1 21272
#define RaptorDialogCGBPal3c2 14930
#define RaptorDialogCGBPal3c3 125

/* Gameboy Color palette 4 */
#define RaptorDialogCGBPal4c0 32767
#define RaptorDialogCGBPal4c1 21272
#define RaptorDialogCGBPal4c2 6596
#define RaptorDialogCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define RaptorDialogCGBPal5c0 32767
#define RaptorDialogCGBPal5c1 21272
#define RaptorDialogCGBPal5c2 575
#define RaptorDialogCGBPal5c3 4228

/* Gameboy Color palette 6 */
#define RaptorDialogCGBPal6c0 6076
#define RaptorDialogCGBPal6c1 8935
#define RaptorDialogCGBPal6c2 6596
#define RaptorDialogCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define RaptorDialogCGBPal7c0 32767
#define RaptorDialogCGBPal7c1 799
#define RaptorDialogCGBPal7c2 502
#define RaptorDialogCGBPal7c3 4228
/* CGBpalette entries. */
extern const unsigned char RaptorDialogCGB[];
/* Start of tile array. */
extern const unsigned char RaptorDialog[];

#endif

/* End of RAPTORDIALOGTILES.H */
