/*

 BRAVOSHIP1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __BravoShip1_h_INCLUDE
#define __BravoShip1_h_INCLUDE

/* Bank of tiles. */
#define BravoShip1TilesBank 5

/* Super Gameboy palette 0 */
#define BravoShip1TilesSGBPal0c0 6076
#define BravoShip1TilesSGBPal0c1 8935
#define BravoShip1TilesSGBPal0c2 6596
#define BravoShip1TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BravoShip1TilesSGBPal1c0 6076
#define BravoShip1TilesSGBPal1c1 8935
#define BravoShip1TilesSGBPal1c2 6596
#define BravoShip1TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BravoShip1TilesSGBPal2c0 6076
#define BravoShip1TilesSGBPal2c1 8935
#define BravoShip1TilesSGBPal2c2 6596
#define BravoShip1TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BravoShip1TilesSGBPal3c0 6076
#define BravoShip1TilesSGBPal3c1 8935
#define BravoShip1TilesSGBPal3c2 6596
#define BravoShip1TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BravoShip1TilesCGBPal0c0 6076
#define BravoShip1TilesCGBPal0c1 8935
#define BravoShip1TilesCGBPal0c2 6596
#define BravoShip1TilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define BravoShip1TilesCGBPal1c0 992
#define BravoShip1TilesCGBPal1c1 32489
#define BravoShip1TilesCGBPal1c2 15855
#define BravoShip1TilesCGBPal1c3 5285

/* Gameboy Color palette 2 */
#define BravoShip1TilesCGBPal2c0 6076
#define BravoShip1TilesCGBPal2c1 8935
#define BravoShip1TilesCGBPal2c2 6596
#define BravoShip1TilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BravoShip1TilesCGBPal3c0 6076
#define BravoShip1TilesCGBPal3c1 8935
#define BravoShip1TilesCGBPal3c2 6596
#define BravoShip1TilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BravoShip1TilesCGBPal4c0 6076
#define BravoShip1TilesCGBPal4c1 8935
#define BravoShip1TilesCGBPal4c2 6596
#define BravoShip1TilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BravoShip1TilesCGBPal5c0 6076
#define BravoShip1TilesCGBPal5c1 8935
#define BravoShip1TilesCGBPal5c2 6596
#define BravoShip1TilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BravoShip1TilesCGBPal6c0 6076
#define BravoShip1TilesCGBPal6c1 8935
#define BravoShip1TilesCGBPal6c2 6596
#define BravoShip1TilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BravoShip1TilesCGBPal7c0 6076
#define BravoShip1TilesCGBPal7c1 8935
#define BravoShip1TilesCGBPal7c2 6596
#define BravoShip1TilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const void __bank_BravoShip1TilesCGB;
extern const unsigned char BravoShip1TilesCGB[];
/* Start of tile array. */
extern const void __bank_BravoShip1Tiles;
extern const unsigned char BravoShip1Tiles[];

#endif

/* End of BRAVOSHIP1.H */
