/*

 CURSOR.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Cursor_h_INCLUDE
#define __Cursor_h_INCLUDE

/* Bank of tiles. */
#define CursorTileBank 0

/* Super Gameboy palette 0 */
#define CursorTileSGBPal0c0 6076
#define CursorTileSGBPal0c1 8935
#define CursorTileSGBPal0c2 6596
#define CursorTileSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define CursorTileSGBPal1c0 6076
#define CursorTileSGBPal1c1 8935
#define CursorTileSGBPal1c2 6596
#define CursorTileSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define CursorTileSGBPal2c0 6076
#define CursorTileSGBPal2c1 8935
#define CursorTileSGBPal2c2 6596
#define CursorTileSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define CursorTileSGBPal3c0 6076
#define CursorTileSGBPal3c1 8935
#define CursorTileSGBPal3c2 6596
#define CursorTileSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define CursorTileCGBPal0c0 32767
#define CursorTileCGBPal0c1 5919
#define CursorTileCGBPal0c2 666
#define CursorTileCGBPal0c3 0

/* Gameboy Color palette 1 */
#define CursorTileCGBPal1c0 6076
#define CursorTileCGBPal1c1 8935
#define CursorTileCGBPal1c2 6596
#define CursorTileCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define CursorTileCGBPal2c0 6076
#define CursorTileCGBPal2c1 8935
#define CursorTileCGBPal2c2 6596
#define CursorTileCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define CursorTileCGBPal3c0 6076
#define CursorTileCGBPal3c1 8935
#define CursorTileCGBPal3c2 6596
#define CursorTileCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define CursorTileCGBPal4c0 6076
#define CursorTileCGBPal4c1 8935
#define CursorTileCGBPal4c2 6596
#define CursorTileCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define CursorTileCGBPal5c0 6076
#define CursorTileCGBPal5c1 8935
#define CursorTileCGBPal5c2 6596
#define CursorTileCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define CursorTileCGBPal6c0 6076
#define CursorTileCGBPal6c1 8935
#define CursorTileCGBPal6c2 6596
#define CursorTileCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define CursorTileCGBPal7c0 6076
#define CursorTileCGBPal7c1 8935
#define CursorTileCGBPal7c2 6596
#define CursorTileCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char CursorTileCGB[];
extern const unsigned char CursorTileTLE0[];

#endif

/* End of CURSOR.H */
