/*

 CURSOR.C

 Tile Source File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
const unsigned char CursorTileCGB[] =
{
  0x00
};
const unsigned char CursorTileTLE0[] =
{
  0x00,0x18,0x18,0x00,0x18,0x00,0x66,0x81,
  0x66,0x81,0x18,0x00,0x18,0x00,0x00,0x18
};

/* End of CURSOR.C */
