/*

 CURSOR.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Cursor_h_INCLUDE
#define __Cursor_h_INCLUDE

/* Bank of tiles. */
#define CursorTileBank 2
extern const void __bank_CursorTileTLE0;
extern const unsigned char CursorTileTLE0[];

#endif

/* End of CURSOR.H */
