#pragma bank 1

/*

 CURSOR.C

 Tile Source File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

const void __at(1) __bank_CursorTileTLE0;
const unsigned char CursorTileTLE0[] =
{
  0x00,0x18,0x18,0x00,0x18,0x00,0x66,0x81,
  0x66,0x81,0x18,0x00,0x18,0x00,0x00,0x18
};

/* End of CURSOR.C */
