/*

 MCHBULLET.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __MchBullet_h_INCLUDE
#define __MchBullet_h_INCLUDE

/* Bank of tiles. */
#define MchBulletBank 0

/* Super Gameboy palette 0 */
#define MchBulletSGBPal0c0 6076
#define MchBulletSGBPal0c1 8935
#define MchBulletSGBPal0c2 6596
#define MchBulletSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define MchBulletSGBPal1c0 6076
#define MchBulletSGBPal1c1 8935
#define MchBulletSGBPal1c2 6596
#define MchBulletSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define MchBulletSGBPal2c0 6076
#define MchBulletSGBPal2c1 8935
#define MchBulletSGBPal2c2 6596
#define MchBulletSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define MchBulletSGBPal3c0 6076
#define MchBulletSGBPal3c1 8935
#define MchBulletSGBPal3c2 6596
#define MchBulletSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define MchBulletCGBPal0c0 32767
#define MchBulletCGBPal0c1 25368
#define MchBulletCGBPal0c2 15855
#define MchBulletCGBPal0c3 5285

/* Gameboy Color palette 1 */
#define MchBulletCGBPal1c0 6076
#define MchBulletCGBPal1c1 8935
#define MchBulletCGBPal1c2 6596
#define MchBulletCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define MchBulletCGBPal2c0 6076
#define MchBulletCGBPal2c1 8935
#define MchBulletCGBPal2c2 6596
#define MchBulletCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define MchBulletCGBPal3c0 6076
#define MchBulletCGBPal3c1 8935
#define MchBulletCGBPal3c2 6596
#define MchBulletCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define MchBulletCGBPal4c0 6076
#define MchBulletCGBPal4c1 8935
#define MchBulletCGBPal4c2 6596
#define MchBulletCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define MchBulletCGBPal5c0 6076
#define MchBulletCGBPal5c1 8935
#define MchBulletCGBPal5c2 6596
#define MchBulletCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define MchBulletCGBPal6c0 6076
#define MchBulletCGBPal6c1 8935
#define MchBulletCGBPal6c2 6596
#define MchBulletCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define MchBulletCGBPal7c0 6076
#define MchBulletCGBPal7c1 8935
#define MchBulletCGBPal7c2 6596
#define MchBulletCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char MchBulletCGB[];
extern const unsigned char MchBulletTLE0[];
extern const unsigned char MchBulletTLE1[];

#endif

/* End of MCHBULLET.H */
