/*

 MCHBULLET.C

 Tile Source File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
const unsigned char MchBulletCGB[] =
{
  0x00,0x00
};
const unsigned char MchBulletTLE0[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x41,
  0x82,0x00,0x00,0x00,0x00,0x00,0x00,0x00
};
const unsigned char MchBulletTLE1[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x82,0x00,
  0x00,0x41,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of MCHBULLET.C */
