/*

 MCHBULLET.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __MchBullet_h_INCLUDE
#define __MchBullet_h_INCLUDE

/* Bank of tiles. */
#define MchBulletBank 2
extern const void __bank_MchBulletTLE0;
extern const unsigned char MchBulletTLE0[];
extern const void __bank_MchBulletTLE1;
extern const unsigned char MchBulletTLE1[];

#endif

/* End of MCHBULLET.H */
