/*

 WPROJECTILES.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __WProjectiles_h_INCLUDE
#define __WProjectiles_h_INCLUDE

/* Bank of tiles. */
#define WProjectilesTilesBank 2

/* Super Gameboy palette 0 */
#define WProjectilesTilesSGBPal0c0 6076
#define WProjectilesTilesSGBPal0c1 8935
#define WProjectilesTilesSGBPal0c2 6596
#define WProjectilesTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define WProjectilesTilesSGBPal1c0 6076
#define WProjectilesTilesSGBPal1c1 8935
#define WProjectilesTilesSGBPal1c2 6596
#define WProjectilesTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define WProjectilesTilesSGBPal2c0 6076
#define WProjectilesTilesSGBPal2c1 8935
#define WProjectilesTilesSGBPal2c2 6596
#define WProjectilesTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define WProjectilesTilesSGBPal3c0 6076
#define WProjectilesTilesSGBPal3c1 8935
#define WProjectilesTilesSGBPal3c2 6596
#define WProjectilesTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define WProjectilesTilesCGBPal0c0 992
#define WProjectilesTilesCGBPal0c1 32767
#define WProjectilesTilesCGBPal0c2 15855
#define WProjectilesTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define WProjectilesTilesCGBPal1c0 992
#define WProjectilesTilesCGBPal1c1 32767
#define WProjectilesTilesCGBPal1c2 799
#define WProjectilesTilesCGBPal1c3 502

/* Gameboy Color palette 2 */
#define WProjectilesTilesCGBPal2c0 992
#define WProjectilesTilesCGBPal2c1 15855
#define WProjectilesTilesCGBPal2c2 452
#define WProjectilesTilesCGBPal2c3 502

/* Gameboy Color palette 3 */
#define WProjectilesTilesCGBPal3c0 992
#define WProjectilesTilesCGBPal3c1 799
#define WProjectilesTilesCGBPal3c2 15855
#define WProjectilesTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define WProjectilesTilesCGBPal4c0 992
#define WProjectilesTilesCGBPal4c1 21140
#define WProjectilesTilesCGBPal4c2 15855
#define WProjectilesTilesCGBPal4c3 10570

/* Gameboy Color palette 5 */
#define WProjectilesTilesCGBPal5c0 6076
#define WProjectilesTilesCGBPal5c1 8935
#define WProjectilesTilesCGBPal5c2 6596
#define WProjectilesTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define WProjectilesTilesCGBPal6c0 6076
#define WProjectilesTilesCGBPal6c1 8935
#define WProjectilesTilesCGBPal6c2 6596
#define WProjectilesTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define WProjectilesTilesCGBPal7c0 6076
#define WProjectilesTilesCGBPal7c1 8935
#define WProjectilesTilesCGBPal7c2 6596
#define WProjectilesTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const void __bank_WProjectilesTilesCGB;
extern const unsigned char WProjectilesTilesCGB[];
extern const void __bank_WProjectilesTilesTLE0;
extern const unsigned char WProjectilesTilesTLE0[];
extern const void __bank_WProjectilesTilesTLE1;
extern const unsigned char WProjectilesTilesTLE1[];
extern const void __bank_WProjectilesTilesTLE2;
extern const unsigned char WProjectilesTilesTLE2[];
extern const void __bank_WProjectilesTilesTLE3;
extern const unsigned char WProjectilesTilesTLE3[];
extern const void __bank_WProjectilesTilesTLE4;
extern const unsigned char WProjectilesTilesTLE4[];
extern const void __bank_WProjectilesTilesTLE5;
extern const unsigned char WProjectilesTilesTLE5[];

#endif

/* End of WPROJECTILES.H */
